contiv_cert_dir: "/etc/contiv/certs"
contiv_netmaster_port: 9999
contiv_cni_version: 1.0.1
contiv_k8s_api_server: "https://{{ hostvars[groups['kube-master'][0]]['ansible_default_ipv4']['address'] }}:{{ kube_apiserver_port }}"

# Parameters for Contiv api-proxy
contiv_enable_api_proxy: true
contiv_api_proxy_port: 10000
contiv_generate_certificate: true

# Forwarding mode: bridge or routing
contiv_fwd_mode: routing

# Fabric mode: aci, aci-opflex or default
contiv_fabric_mode: default

# Dataplane interface
contiv_vlan_interface: ""

# Default network configuration
contiv_networks:
  - name: contivh1
    subnet: "10.233.128.0/18"
    gateway: "10.233.128.1"
    nw_type: infra
  - name: default-net
    subnet: "{{ kube_pods_subnet }}"
    gateway: "{{ kube_pods_subnet|ipaddr('net')|ipaddr(1)|ipaddr('address') }}"
    pkt_tag: 10
