- name: Contiv | Create Kubernetes resources
  kube:
    name: "{{ item.item.name }}"
    namespace: "{{ system_namespace }}"
    kubectl: "{{ bin_dir }}/kubectl"
    resource: "{{ item.item.type }}"
    filename: "{{ contiv_config_dir }}/{{ item.item.name }}.yml"
    state: "{{ item.changed | ternary('latest','present') }}"
  with_items: "{{ contiv_manifests_results.results }}"

- include: configure.yml
